name: CI
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build Images and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Install depedencies
        uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true


      - name: Build Docker Image and Deploy to k8s
        run: |
          gcloud auth configure-docker --quiet
          docker build . -f Dockerfile -t "nasr/nginx:$$(git rev-parse --short HEAD)"
          docker tag "nasr/nginx:$$(git rev-parse --short HEAD)" gcr.io/nasr-learn-286800/nasr/nginx:latest
          docker push "gcr.io/nasr-learn-286800/nasr/nginx"
